[package]
name = "zero-os"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
multiboot2 = { version="0.23.1", default-features = false }
uart_16550 = "0.3"
spin = "0.9"

[dependencies.noto-sans-mono-bitmap]
version = "0.3.1"
features = ["size_24"]